[package]
name = "win"
version = "0.1.0"
edition = "2021"

[dependencies]
tauri = { version = "2.5.1", features = ["protocol-asset"] }
tauri-plugin-shell = "2.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[build-dependencies]
tauri-build = { version = "2.2.0", features = [] }
